### ISSUE TITLE
npm start fail due to old launchpad dependency

### ISSUE THREAD

**Issue by gasolin** [devtools-html/devtools-reps#43]
more details on https://github.com/devtools-html/devtools-core/issues/89

**Comment by gasolin** [comment]
Still got errors after upgrade launchpad to 0.0.24

```
ERROR in ./src/launchpad/components/Header.js
Module parse failed: /home/gasolin/devtools-reps/src/launchpad/components/Header.js Unexpected token (71:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (71:6)
    at Parser.pp$4.raise (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
 @ ./src/launchpad/components/Console.js 8:29-48

ERROR in ./src/launchpad/actions/expressions.js
Module parse failed: /home/gasolin/devtools-reps/src/launchpad/actions/expressions.js Unexpected token (5:15)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (5:15)
    at Parser.pp$4.raise (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseReturnStatement (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:839:57)
    at Parser.pp$1.parseStatement (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:699:34)
    at Parser.pp$1.parseBlock (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$1.parseFunctionStatement (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:818:17)
    at Parser.pp$1.parseStatement (/home/gasolin/devtools-reps/node_modules/webpack/node_modules/acorn/dist/acorn.js:694:19)
 @ ./src/launchpad/actions/index.js 1:20-44
```

**Comment by juliandescottes** [comment]
We need to refine the babel exclusion regexp in devtools-launchpad. I'll submit a PR for launchpad soon.

**Comment by juliandescottes** [comment]
This should now be fixed @gasolin feel free to reopen if it still fails for you.

**Comment by gasolin** [comment]
works pretty well. It's really nice to see the connection tips banner (`First time connecting to Firefox`)  thanks!
